<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllArticles()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('a')
            ->from('AppBundle:Article', 'a')
            ->join('a.category', 'cat')
            ->orderBy('a.publicationDate', 'DESC');
        return $qb->getQuery();
    }

    public function findByCategory($id)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('a')
            ->from('AppBundle:Article', 'a')
            ->where($qb->expr()->eq('a.category', $id))
            ->join('a.category', 'cat')
            ->orderBy('a.publicationDate', 'DESC');
        return $qb->getQuery();
    }

    public function findTodaysBest($today, $number)
    {
        $from = new \DateTime($today->format("Y-m-d")." 00:00:00");
        $to   = new \DateTime($today->format("Y-m-d")." 23:59:59");
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('a')
            ->from('AppBundle:Article', 'a')
            ->andWhere('a.publicationDate BETWEEN :from AND :to')
            ->setParameter('from', $from)
            ->setParameter('to', $to)
            ->orderBy('a.views', 'DESC')
            ->setMaxResults($number);
        return $qb->getQuery()->getResult();
    }
}
