app:
    resource: "@AppBundle/Controller"
    type:     annotation

logout:
    path: /logout

kms_froala_editor:
    resource: '@KMSFroalaEditorBundle/Resources/config/routing.yml'
    prefix:   /froalaeditor
