about:
    path:     /{_locale}/about
    defaults: { _controller: AppBundle:About:index }
    requirements:
        _locale: en|ru|be
access_denied:
    path:     /login
    defaults: { _controller: AppBundle:Login:login }
    requirements:
        _locale: en|ru|be
admin:
    path:     /{_locale}/admin
    defaults: { _controller: AppBundle:Admin:admin}
    requirements:
        _locale: en|ru|be
ajaxUsers:
    path:     /{_locale}/ajax/users
    defaults: { _controller: AppBundle:AjaxUsers:usersList}
    requirements:
        _locale: en|ru|be
ajaxAryicles:
    path:     /{_locale}/ajax/articles
    defaults: { _controller: AppBundle:AjaxArticles:articlesList}
    requirements:
        _locale: en|ru|be
default:
    path:     /
    defaults: { _controller: AppBundle:Login:login }
    requirements:
        _locale: en|ru|be
create_article:
    path:     /{_locale}/create
    defaults: { _controller: AppBundle:Article:creation }
    requirements:
        _locale: en|ru|be
login:
    path:     /{_locale}/login
    defaults: { _controller: AppBundle:Login:login }
    requirements:
        _locale: en|ru|be
logout:
    path: /logout
moderating_articles:
    path:     /{_locale}/moderating_articles
    defaults: { _controller: AppBundle:Moderator:moderatingArticles}
    requirements:
        _locale: en|ru|be
news_default:
    path:     /news
    defaults: { _controller: AppBundle:MainPage:index, _locale: en }
    requirements:
        _locale: en|ru|be
news:
    path:     /{_locale}/news
    defaults: { _controller: AppBundle:MainPage:index }
    requirements:
        _locale: en|ru|be
article:
    path:     /{_locale}/news/{slug}
    defaults: { _controller: AppBundle:News:index}
    requirements:
        _locale: en|ru|be
recovery:
    path:     /{_locale}/recovery
    defaults: { _controller: AppBundle:PasswordRecovery:recovery }
    requirements:
        _locale: en|ru|be
reset_password:
    path:     /{_locale}/reset/{token}
    defaults: { _controller: AppBundle:PasswordRecovery:reset }
    requirements:
        _locale: en|ru|be
user_registration:
    path:     /{_locale}/register
    defaults: { _controller: AppBundle:Registration:register }
    requirements:
        _locale: en|ru|be
register_confirmation:
    path:     /{_locale}/register/{token}
    defaults: { _controller: AppBundle:Registration:confirm }
    requirements:
        _locale: en|ru|be

kms_froala_editor:
    resource: '@KMSFroalaEditorBundle/Resources/config/routing.yml'
    prefix:   /froalaeditor
