# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    access_denied_url: /access_denied

    providers:
        user_provider:
            entity:
                class: AppBundle:User
                property: email


    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                provider: user_provider
                username_parameter: _email
                always_use_default_target_path: true
                default_target_path:            /
            logout:
                path:   logout
                target: login

    access_control:
        - { path: /about, roles: ROLE_USER}
        - { path: /ajax, roles: ROLE_USER}
        - { path: /search, roles: ROLE_USER}
        - { path: /category/delete, roles: ROLE_MODERATOR}
        - { path: /category/edit, roles: ROLE_MODERATOR}
        - { path: /category/new, roles: ROLE_MODERATOR}
        - { path: /article/new, roles: ROLE_MODERATOR}
        - { path: /article/delete, roles: ROLE_MODERATOR}
        - { path: /article/edit, roles: ROLE_MODERATOR}
        - { path: /article/create, roles: ROLE_MODERATOR}
        - { path: /category, roles: ROLE_USER}
        - { path: /article, roles: ROLE_USER}
        - { path: /upload, roles: ROLE_USER}
        - { path: /user, roles: ROLE_ADMIN }

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_MODERATOR:   ROLE_USER
        ROLE_ADMIN:       ROLE_MODERATOR